### ISSUE TITLE
Cannot read property 'url' of undefined

### ISSUE THREAD

**Issue by Auliyaa** [Auliyaa/discord-genialo#10]
Full stacktrace:

```
0|genialo  | TypeError: Cannot read property 'url' of undefined
0|genialo  |     at player.handle_play (/home/pi/bots/discord-genialo/src/player/player.js:93:84)
0|genialo  |     at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by Auliyaa** [comment]
Can not reproduce
