### ISSUE TITLE
Error Could not extract html5player key

### ISSUE THREAD

**Issue by Auliyaa** [Auliyaa/discord-genialo#12]
Stack trace:

```
0|genialo  | Could not extract html5player key: https://www.youtube.com/s/player/5168268b/player_ias.vflset/en_US/base.js
0|genialo  | TypeError: Cannot read property 'title' of undefined
0|genialo  |     at player.handle_play (/home/pi/bots/discord-genialo/src/player/player.js:93:67)
0|genialo  |     at runMicrotasks (<anonymous>)
0|genialo  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by Auliyaa** [comment]
3.1.2 released
