### ISSUE TITLE
fields.flat is not a function

### ISSUE THREAD

**Issue by Auliyaa** [Auliyaa/discord-genialo#7]
### Steps to reproduce

- Run the bot
- In any channel this bot has access to, type-int he following URL: https://store.steampowered.com/app/1146940/I_will_eat_you/

### Error log
```
> discord-genialo@3.0.0 bot /home/auliyaa/dev/discord-genialo
> node src/index.js ./genialo.conf

/home/auliyaa/dev/discord-genialo/node_modules/discord.js/src/structures/MessageEmbed.js:433
      .flat(2)
       ^

TypeError: fields.flat is not a function
    at Function.normalizeFields (/home/auliyaa/dev/discord-genialo/node_modules/discord.js/src/structures/MessageEmbed.js:433:8)
    at MessageEmbed.setup (/home/auliyaa/dev/discord-genialo/node_modules/discord.js/src/structures/MessageEmbed.js:68:50)
    at new MessageEmbed (/home/auliyaa/dev/discord-genialo/node_modules/discord.js/src/structures/MessageEmbed.js:11:10)
    at embeds.map.e (/home/auliyaa/dev/discord-genialo/node_modules/discord.js/src/structures/Message.js:101:48)
    at Array.map (<anonymous>)
    at Message._patch (/home/auliyaa/dev/discord-genialo/node_modules/discord.js/src/structures/Message.js:101:39)
    at new Message (/home/auliyaa/dev/discord-genialo/node_modules/discord.js/src/structures/Message.js:43:20)
    at MessageManager.add (/home/auliyaa/dev/discord-genialo/node_modules/discord.js/src/managers/BaseManager.js:49:32)
    at MessageManager.add (/home/auliyaa/dev/discord-genialo/node_modules/discord.js/src/managers/MessageManager.js:29:18)
    at MessageCreateAction.handle (/home/auliyaa/dev/discord-genialo/node_modules/discord.js/src/client/actions/MessageCreate.js:13:40)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! discord-genialo@3.0.0 bot: `node src/index.js ./genialo.conf`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the discord-genialo@3.0.0 bot script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/auliyaa/.npm/_logs/2020-03-07T17_06_40_933Z-debug.log
```

**Comment by Fiusen** [comment]
same issue here

**Comment by Auliyaa** [comment]
Please see: https://github.com/discordjs/discord.js/issues/3910

Currently patching this locally until a proper fix is handled on their side.
