### ISSUE TITLE
[!gamedeals] Cannot read property 'send' of undefined

### ISSUE THREAD

**Issue by Auliyaa** [Auliyaa/discord-genialo#9]
Full stack trace:

```
0|genialo  | TypeError: Cannot read property 'send' of undefined
0|genialo  |     at gamedeals.post (/home/pi/bots/discord-genialo/src/gamedeals/gamedeals.js:52:18)
0|genialo  |     at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by Auliyaa** [comment]
fixed in 3.0.4
